# Generated by Django 5.1.6 on 2025-03-03 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('daily_trainer', 'Daily Trainer'), ('race', 'Race'), ('trail', 'Trail'), ('stability', 'Stability')], max_length=50)),
                ('weight', models.FloatField()),
                ('drop', models.FloatField()),
                ('pronation', models.CharField(choices=[('neutral', 'Neutral'), ('stability', 'Stability')], max_length=20)),
                ('cushioning', models.CharField(choices=[('minimalist', 'Minimalist'), ('max_cushion', 'Max Cushion'), ('energy_return', 'Energy Return')], max_length=20)),
                ('terrain', models.CharField(choices=[('road', 'Road'), ('trail', 'Trail')], max_length=20)),
                ('plate', models.BooleanField(default=False)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommender.brand')),
            ],
        ),
    ]
