# Generated by Django 5.1.6 on 2025-03-23 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunningShoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('Nike', 'Nike'), ('Adidas', 'Adidas'), ('Brooks', 'Brooks'), ('Saucony', 'Saucony'), ('Hoka', 'Hoka'), ('ON', 'ON')], max_length=50)),
                ('model', models.CharField(max_length=100)),
                ('stride_type', models.CharField(choices=[('Forefoot', 'Forefoot'), ('Midfoot', 'Midfoot'), ('Heel', 'Heel')], max_length=50)),
                ('pronation', models.CharField(choices=[('Neutral', 'Neutral'), ('Overpronation', 'Overpronation'), ('Supination', 'Supination')], max_length=50)),
                ('cushioning', models.CharField(choices=[('Minimalist', 'Minimalist'), ('Moderate', 'Moderate'), ('Max Cushion', 'Max Cushion')], max_length=50)),
                ('foot_shape', models.CharField(choices=[('Narrow', 'Narrow'), ('Standard', 'Standard'), ('Wide', 'Wide')], max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='shoe',
            name='brand',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Shoe',
        ),
    ]
